### PR TITLE
Fetch issues and pull requests in parallel.

### PR DESCRIPTION
**Pull request by calavera**
TODO:
- [x] Use GitHub's hypermedia links to calculate the total.
- [x] Respect api rate limits.
- [x] Add new tests.

### CODE REVIEW

**Comment by icecrime** [comment]
SGTM, but it seems `github.com/octokit/go-octokit/octokit` is missing from the `Godeps`.

**Comment by calavera** [comment]
oh, right, thanks!

**Comment by calavera** [comment]
@icecrime do you mind to add this repo to travis-ci now that we have some tests? :smile: 

It should be ready to merge but I'd like to see that green dot.

**Comment by icecrime** [comment]
I just did, I don't know if it's expecting something to move to trigger.

**Comment by calavera** [comment]
I can trigger it with a push, thanks!

**Comment by calavera** [comment]
:tada:

**Comment by icecrime** [comment]
:dancer:

**Pull request merged**
