### PR TITLE
Collect more information about issues and pull requests.

### PR DESCRIPTION
**Pull request by calavera**
@icecrime I've started to add new series to be able to add more metrics to the dashboard.
I'm keeping the old series around to not break the current dashboard, but we should be able to calculate the same results with the new series.
Unfortunately, the graphite driver is broken because we're storing other additional information besides counters. I'd rather remove it, tbh. Thoughts?

TODO:
- [x] Keep information about when they where created and their state.
- [x] Do not count extra issues that are associated to pull requests.
- [x] Keep information about labels.
- [x] Add additional tests.
- [x] Remove graphite driver.

Signed-off-by: David Calavera david.calavera@gmail.com

### CODE REVIEW

**Comment by icecrime** [comment]
I think it's fine to kill Graphite: we only used it in the beginning, but @crosbymichael forced us into Influx (:wink:).

**Comment by icecrime** [comment]
LGTM!

**Comment by calavera** [comment]
@icecrime I think with this we'll be able to measure rates and proportions. Times are going to be more tricky because we don't have information about when labels, issues and prs change their state.

What do you think about merge this and running some tests with real data tomorrow or Friday?

**Comment by icecrime** [comment]
SGTM! We can also just setup an influxdb somewhere else if we don't want to risk loosing data (but truth is, it wouldn't be tat bad) :-)

**Comment by crosbymichael** [comment]
It's just a container so commit it then pull it down onto your machine.  WE ARE DOING THIS FOR A REASON, CONTAINERS ARE GOOD.

**Pull request merged**
